### ISSUE TITLE
Light/Dark mode use windows mode issue 

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#4090] opened 2020-05-24 14:35 UTC
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.5.146

### 🐞 Actual behavior

If the "use my Windows mode" option is selected for the Light/Dark mode setting, changing the Windows color setting from dark to light (or the opposite) will not reflect the in the app until you access the preferences view or restart it.

### 💯 Expected behavior
Changing the color setting in windows from light to dark (or the other way around) should apply the change to the desktop app "live" without the need to access the Preferences view or restart the app

### 🔨 Steps to reproduce
1. Start the app
2. Select "use my Windows mode" option for the Light/Dark mode setting
3. Change the color setting in Windows 
4. Bring the app back into focus to see if the mode changed (it will not)
5. Access the Preferences view and the mode will change (or restart the app)

**Comment by skel35** [comment] 2020-05-25 07:51
duplicate of #3450

**Closed by skel35** 2020-05-25 07:51 UTC
