### ISSUE TITLE
Do not disturb

### ISSUE THREAD

**Issue by jirizaj** [toggl-open-source/toggldesktop#2359] opened 2018-01-21 18:58 UTC
Hello guys, tracking reminder is really cool feature, which saved me many times when I forgot to track my time. However, I use my computer even for personal things like watching a movie, when I don't want to be disturbed. Sure, I can just turn toggl off, but I have to keep in mind that I need to turn it on, which fails from time to time 😃. And setting reminder time limit is not an option for an entrepreneur who often works during the night. 

It would be amazing to have some option to disable the reminder just for some time. Set e.g. I don't want to be disturbed for next two hours - easily accessible from the UI.

**Comment by IndrekV** [comment] 2018-01-22 12:32
I like the idea. I've seen similar functionality in other applications that allow disabling certain functionality for the rest of the day or some other one-time timeframe. We'll consider this request. Thank you for sharing your thoughts.

**Comment by skel35** [comment] 2020-05-22 10:49
duplicate of #3568

**Closed by skel35** 2020-05-22 10:49 UTC
