### ISSUE TITLE
Mini timer not staying on top

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2045] opened 2016-11-10 12:21 UTC
This happens when user clicks any empty space on the bottom task bar. The Minitimer should be on top but goes behind the taskbar

![minitimer_not_ontop](https://user-images.githubusercontent.com/842229/54905297-5f9d4680-4ee9-11e9-89f2-044afedef297.png)

User comment:
>I managed to find the logic of the below described bug.
If I click on a non icon are on the taskbar, the mini timer gets behind
the taskbar. Left click or right click both works. So e.g. I click on
start menu, an empty are, on clock - this bug happens. If I left click
on an icon, e.g. Skype, then the bug is not happening. If I right click
on an inc, e.g. Skpye, the bug is happening.

More info in case: 382375

**Comment by ruant** [comment] 2019-10-08 09:19
Any progress on this?
Perhaps just smash the mini tracker inside the taskbar instead, then it will always be available.

**Comment by skel35** [comment] 2019-10-08 09:25
Unfortunately, we're hitting the limitations of Windows here.
It should be possible to fit a super-small mini-timer inside the taskbar icon (for like <25% of the icon size), but we're not sure it would look good.
@ruant If you have any examples of other apps doing something similar (some UI over/inside taskbar), please share with us, that would be really helpful.

**Comment by MartinBriza** [comment] 2019-10-08 09:46
BatteryBar does something like this:

![image](https://user-images.githubusercontent.com/3977440/66385752-4fe6da80-e9c1-11e9-913c-cd4c97577a11.png)

https://batterybarpro.com/

**Comment by skel35** [comment] 2019-10-08 10:11
Wow, thanks @MartinBriza!
Microsoft says the API for doing this is deprecated starting from Windows 7, but BatteryBar works on my latest Windows 10 without any problems. Gotta trust the docs less, I should try to play around with that old API.

**Comment by Jarpetnee** [comment] 2019-10-16 05:06
Hi @skel35, I just want to 1+ this feature request. My only issue with the windows application is the mini timer blocking stuff I need to see. A taskbar mini-min-timer would be great value — or even a mini-timer that stays on top even after the taskbar is given focus.

**Comment by markcerv** [comment] 2020-03-06 01:23
+1 I can't find a good place to stick the mini timer.  I WANT to keep it on the taskbar/near the date/time icons etc.   Please come up w/ a way to do this.

**Comment by skel35** [comment] 2020-05-13 13:13
Closing this issue as a duplicate of #3142.

**Closed by skel35** 2020-05-13 13:13 UTC
Labels: bug, windows
