### ISSUE TITLE
Windows Timeline - Add new time entries with click and drag

### ISSUE THREAD

**Issue by GitMurf** [toggl-open-source/toggldesktop#4629] opened 2020-10-30 19:54 UTC
### 💻 Environment

Platform: Windows

### 📒 Description

I want to be able to add new time entries by clicking and dragging on the timeline the time that I need the entry added. So I could for example click around 10am and start dragging to around 10:30am and it would create a time entry. Then I can further modify the start and end time after it is created if it wasn't precisely the time I wanted (normal behavior as of today with current time entries).

### ⭐️ Why do you want this?

Currently I could "hack" (as seen in my GIF below) by adding a new "dummy" entry to the beginning of my day so that then I could use the "+" sign on the left to add a new entry between the start of day and my first time entry I currently have for the day and then can resize accordingly to the size/time I want.

But the problem is by default you can't use the "+" unless there is already two time entries that you can use the "+" to add a new entry between. So adding a "pseduo" entry at start of day is "hacky' way around that but not ideal.

All the time I start working on stuff and forget to start my timer and then later I go "oh I want to add time from that meeting earlier this morning" but I can't do that without manually creating it through the normal "new entry" options.

![Add new time with click and drag](https://user-images.githubusercontent.com/64155612/97750881-d380d700-1aae-11eb-9acd-fd9aeb5af8f1.gif)

**Comment by skel35** [comment] 2020-11-05 09:43
Thanks for the report!
We're planning to implement click-dragging soon.
I'll close this as a duplicate of #4622.

**Closed by skel35** 2020-11-05 09:43 UTC

**Comment by GitMurf** [comment] 2020-11-20 14:56
@skel35 beautiful work on this! The click n drag new time entries is working great! And I also like the ability to just click and it creates a one hour entry at that point. Awesome work!
