### ISSUE TITLE
Abort due to contraint violation

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#2186] opened 2017-06-06 08:18 UTC
/case/481342

The last couple of days I've had an error on Toggl Desktop for Windows. Something like this: ';Abort due to constraint violation';. I then can';t stop/start the time until I close Toggl and re-open it. I'd attach the log, but the ';add screenshot'; button won';t let me do that.

Not sure if related to 2185

**Comment by IndrekV** [comment] 2017-06-14 07:10
Was caused by same thing that caused #2185 is now fixed in stable (7.4.47).

**Comment by jagostinhoCT** [comment] 2019-09-30 14:33
Getting a Constraint violation: UNIQUE constraint failed: time_entries.uid, time_entries.it

**Comment by jurban01** [comment] 2019-09-30 14:37
> Getting a Constraint violation: UNIQUE constraint failed: time_entries.uid, time_entries.it

I have been getting the exact same error all morning today (09/30/19).
![image](https://user-images.githubusercontent.com/25254615/65888871-41b80f00-e36e-11e9-98fa-8b02ef54d76e.png)

**Comment by bluegrass-digital-dev** [comment] 2019-09-30 14:55
Same issue for me all day today 30 September 2019 - see below.

It generally happens when you try and start a previous time entry, to continue working on the same task.

![image](https://user-images.githubusercontent.com/9417393/65890305-f3713300-e3a2-11e9-8f51-4b0fae8c78f1.png)

**Comment by odecroupette** [comment] 2019-09-30 16:58
Same  for me, can't use the app anymore. it keeps time recording. event at restart.
![image](https://user-images.githubusercontent.com/11777854/65899567-4b646580-e3b4-11e9-822d-596108f06ddc.png)

**Comment by muscovitebob** [comment] 2019-09-30 20:23
Having the same issue on macOS today, restarts didn’t fix, or fixed only for a while.

**Comment by lluc** [comment] 2019-10-01 09:09
Same problem on Ubuntu 18.04  :-(
Could you re-open this issue ?

**Comment by NghiaTranUIT** [comment] 2019-10-01 09:13
Sorry guys, we're encountering this outbreak in all platforms. We're investigating it 👍 
Re-opened this ticket.

**Comment by lluc** [comment] 2019-10-01 09:20
Thanks.  :-) :+1:

**Comment by jagostinhoCT** [comment] 2019-10-01 09:52
It is now working for me. All I did was a complete uninstall and reinstall.

**Comment by skel35** [comment] 2019-10-01 09:58
For everyone having the issue: please try to clear the application's cache https://support.toggl.com/en/articles/2410845-clearing-the-local-data-from-toggl-desktop.
It should fix the issue, at least for a while. Meanwhile, we'll make sure the next application update will not allow this error to happen.

**Closed** 2020-01-21 09:10 UTC
Labels: bug
