### ISSUE TITLE
temporarily snooze Remind me to track

### ISSUE THREAD

**Issue by ackvf** [toggl-open-source/toggldesktop#4597] opened 2020-10-24 21:07 UTC
### 💻 Environment

Platform: Windows

### 📒 Description
I appreciate the functionality which reminds me to track time as I forget 100% of time to start tracking, but it would be so much helpful if I could simply snooze the notification for more than 10 minutes, while keeping the default remind timer at 10 minutes. It is rather annoying to have to dismiss the popup every 10 minutes, even when watching a movie.

### ⭐️ Why do you want this?

When I am doing other stuff and the reminder pops up after 10 minutes, I will select "snooze for 60 minutes" and the reminder starts reappearing again in 10 minute intervals when those 60 minutes pass. It could possibly be a select box, so that I can easily choose different snooze time.

**Comment by skel35** [comment] 2020-10-26 08:41
thanks for the request!
closing this as a duplicate of #3568.

**Closed by skel35** 2020-10-26 08:41 UTC
