### ISSUE TITLE
If user is added to a new project the info is not transferred to desktop app

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1800] opened 2016-01-22 15:11 UTC
User reports:

> Every time that I've been added to a new project to book my hours on, it doesn't appear in the desktop app of Toggl.
> I have to go to the online version to add my hours to the project. But even then the desktop doesn't add those hours to that specific project.

Does the info come with websocket?

More info in: 245211

**Comment by IndrekV** [comment] 2016-12-12 13:33
the info does not come with live updates. Restarting app or logging out and back in should solve the issue.

**Comment by skel35** [comment] 2020-05-13 12:33
closing as a duplicate of #2219

**Closed by skel35** 2020-05-13 12:33 UTC
Labels: lib
