### ISSUE TITLE
Pomodoro Break doesn't play well with the Required fields feature

### ISSUE THREAD

**Issue by vedr4n** [toggl-open-source/toggldesktop#2772] opened 2019-01-25 08:57 UTC
Pomodoro Break is a time entry without a project, with just a "Pomodoro Break" as the description. If the workspace has required fields enabled (for projects) that time entry cannot be saved. The API will reject it every time. 

### 💻 Environment
The problem is present in all versions of Toggl Desktop. 

### 🔨 Steps to reproduce

1. Enable the Required fields for time entries feature in your workspace. Check the "Projects" option. 
2. Let Pomodoro kick in and create a Pomodoro Break time entry.
3. Watch the entry be rejected. 

### 📦 Additional info
Related [user convo conversation](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2092037/conversations/20542288503).

**Comment by skel35** [comment] 2020-10-20 21:56
closing as a duplicate of #3747

**Closed by skel35** 2020-10-20 21:56 UTC
Labels: lib, pomodoro
