### ISSUE TITLE
"Load More" Button Issue

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#2230] opened 2017-07-31 15:09 UTC
Case is experiencing an issue where clicking on the Load More button in the Windows app only generates entries from the previous nine days. The button disappears after that.

Case 519139

**Comment by IndrekV** [comment] 2017-08-09 20:48
`Load more` button can be clicked only once per session. If clicked it should fetch entries from the last 60 days and then button disappears.

**Comment by jayvdb** [comment] 2017-10-05 16:18
I have data only back to Oct 2.  When I click Load More on Linux, it only shows back as far as Oct 3, and only shows about half of Oct 3.

**Comment by skel35** [comment] 2020-05-13 13:44
Closing as a duplicate of #3270

**Closed by skel35** 2020-05-13 13:44 UTC
