### ISSUE TITLE
Mac app crashing on start

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#4428] opened 2020-09-18 09:18 UTC
### 💻 Environment

Platform: macOS
OS Version: OS X 10.15.6
Toggl Version: 7.5.268 and 7.5.275

### 🐞 Actual behavior

Two users reached out about the Toggl desktop app for Mac crashing as soon as they try to start it. They say it started happening after the re-branded app was rolled out, updating to the latest app didn't help as well. One user (1498340) shared a video of this happening in their initial message in this[ Intercom thread 🔗 ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481303557067)

### 💯 Expected behavior
The app should not be crashing. 

### 🔨 Steps to reproduce
Was not able to reproduce

### 📦 Additional info
The 2nd user (1947841) shared an error report that poped up for him in this [intercom thread 🔗 ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481303557075)

**Comment by skel35** [comment] 2020-09-18 09:50
maybe the same as #4425 (hard to tell based on the crash report)

**Comment by zdericnina** [comment] 2020-09-18 14:28
another [user](https://app.intercom.com/a/apps/ayixs927/inbox/2759100/conversations/106481303558115) reported the issue with 7.5.275

**Comment by VeljkoTN** [comment] 2020-09-19 19:34
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481303558802)

**Comment by AndrewVebster** [comment] 2020-09-21 08:08
90% sure this is the duplicate of #4425 - behaviour and the app version are the same.

**Comment by skel35** [comment] 2020-09-21 08:09
let's close it then and reopen in case there's any similar report in the fixed version

**Closed by skel35** 2020-09-21 08:09 UTC
Labels: bug, lib

**Comment by AndrewVebster** [comment] 2020-09-21 09:05
The fix was released to stable v7.5.279
