### ISSUE TITLE
Unable to login on Windows Desktop App

### ISSUE THREAD

**Issue by jimmyroberts** [toggl-open-source/toggldesktop#1864] opened 2016-03-22 21:10 UTC
Able to login on the toggl website just fine. Unable to login the Desktop App.

**Comment by amulware** [comment] 2016-03-23 06:22
Are you using regular login (email + password) or do you login with Google?

In either case, what happens when you try to login? Does it give any error messages?

**Comment by jimmyroberts** [comment] 2016-03-23 13:34
It was using the regular login. The error I receive is a red banner at the
top that says, "Login failed. Are you online?"

**Comment by IndrekV** [comment] 2016-03-23 14:01
Make sure Toggl Desktop is not blocked by any security software (antivirus, firewall etc) We've had reports that users needed to whitelist TogglDesktop to allow it to connect with our servers.

**Comment by kickbox** [comment] 2016-05-20 13:34
I have the same issue and I donot have permission to change firewall setting in my company,.. How can I solve this issue?

**Comment by khanshakeeb** [comment] 2016-05-21 14:23
Hi guys,

I am facing similar problem kindly look at screenshot
![bug-toggl-login](https://cloud.githubusercontent.com/assets/303037/15448957/7360c56c-1f89-11e6-8b11-b638245603eb.png)

**Comment by IndrekV** [comment] 2016-05-23 07:38
@khanshakeeb This error can be caused by corrupt local database. Please look at this article for instructions on how to clear local cache. https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/

If the issue persists please send feedback from the app so we get more details.

**Comment by knoxyca** [comment] 2017-02-16 16:52
I have this same issue at work behind a Palo Alto firewall. I believe the issue is likely the Palo Alto device is decrypting the traffic and re-encrypting it with a certificate that my computer trusts, but Toggl does not trust. Are there any settings within Toggl that tell it to trust the certificate even if it doesn't want to?

To test this theory I installed it on a work laptop and accessed TogglDesktop on an internet only connection. This allowed me to login with no issues. When I logged out and then connected to work network, it let me login until I deleted the toggldesktop.db file and then it started giving me the "Login failed. Are you online?" message.

**Comment by jnunez247** [comment] 2017-12-27 15:04
I had the same issue.  but I fixed it by telling it to NOT use Proxy:
Settings -> Preferences -> Proxy -> Do not use proxy -> Save

**Comment by garyng** [comment] 2018-09-24 13:37
https://github.com/toggl/toggldesktop/issues/1864#issuecomment-354126362
> I had the same issue. but I fixed it by telling it to NOT use Proxy:
> Settings -> Preferences -> Proxy -> Do not use proxy -> Save

If you can't login with Google, you can try this. It works on my machine.

**Comment by skel35** [comment] 2020-03-11 13:53
Closing the issue as most of the proxy bugs were fixed (#3307, #3302).
Sometimes Toggl Desktop might not be able to verify an SSL certificate, and in that case, the user can fix it by manually adding their local SSL certificate to `cacert.pem` for Toggl Desktop to recognize: https://github.com/toggl-open-source/toggldesktop/wiki/Getting-Toggl-Desktop-to-work-with-local-proxy.

**Closed by skel35** 2020-03-11 13:53 UTC
Labels: windows

**Comment by netrover** [comment] 2020-05-31 06:32
Having issues trying to connect. It was working correctly and suddenly, the app started working offline. When I try to login, the following error appears:

![image](https://user-images.githubusercontent.com/6636529/83345978-ed3aaa00-a2d5-11ea-9edc-3bd95e554253.png)

After inspecting the log file, seems like an SSL exception is not allowing the app to log me in. Any ideas?
[toggldesktop.log](https://github.com/toggl-open-source/toggldesktop/files/4707191/toggldesktop.log)

**Comment by nipunayf** [comment] 2020-05-31 06:53
Same issue here. It was working fine and suddenly, it is unable to connect. I even tried reinstalling the application and disabling the proxy. None of these solved the issue.

**Comment by FlorinI** [comment] 2020-05-31 07:47
> Having issues trying to connect. It was working correctly and suddenly, the app started working offline. When I try to login, the following error appears:
> 
> ![image](https://user-images.githubusercontent.com/6636529/83345978-ed3aaa00-a2d5-11ea-9edc-3bd95e554253.png)
> 
> After inspecting the log file, seems like an SSL exception is not allowing the app to log me in. Any ideas?
> [toggldesktop.log](https://github.com/toggl-open-source/toggldesktop/files/4707191/toggldesktop.log)

Exact same issue here. Yesterday the desktop app stopped syncing suddenly. I tried clearing the cache both from the menu entry and manually as per the KB, I set the preference to not use a proxy, none of these had any effect. I logged out, I can't log in again.

I am using Google to login. When I press the "LOG IN WITH GOOGLE" button, the browser shows me the correct page to select the correct Google account. When I select it, the browser window says "Received verification code. You may now close this window." and the desktop app says "Login failed. Are you online?"

**Comment by skel35** [comment] 2020-05-31 07:58
The patched app fixes the issue.
Please download a new version of the app
64-bit: https://toggl.github.io/toggldesktop/download/windows64-stable/
32-bit: https://toggl.github.io/toggldesktop/download/windows-stable/

Most of the users can also auto-update from About view or by restarting the app.

**Comment by netrover** [comment] 2020-05-31 08:18
> The patched app fixes the issue.
> Please download a new version of the app
> 64-bit: https://toggl.github.io/toggldesktop/download/windows64-stable/
> 32-bit: https://toggl.github.io/toggldesktop/download/windows-stable/
> 
> Most of the users can also auto-update from About view or by restarting the app.

Installed the Windows x64 version and seems to be working.
Thank you for the prompt response!

**Comment by AlexanderFadeev** [comment] 2020-05-31 08:39
Fixed it by selecting stable in autoupdater branch instead of beta

**Comment by lirankor** [comment] 2020-06-01 08:55
Same here, I lost a few days data by installing the direct link posted above

**Comment by junzhangE3** [comment] 2020-06-01 18:23
> The patched app fixes the issue.
> Please download a new version of the app
> 64-bit: https://toggl.github.io/toggldesktop/download/windows64-stable/
> 32-bit: https://toggl.github.io/toggldesktop/download/windows-stable/
> 
> Most of the users can also auto-update from About view or by restarting the app.

Installed the Windows x64 version and it works, all unsynced time records since last Sat are still there and synced smoothly. Thank you!!

**Comment by lyno1234567** [comment] 2020-06-02 01:24
Same and the patched app also fixed it.  New look on v7.5.162 (64-bit) is good and I love the smaller mini timer, thanks. :)

**Comment by kalelegs** [comment] 2020-06-02 04:36
> The patched app fixes the issue.
> Please download a new version of the app
> 64-bit: https://toggl.github.io/toggldesktop/download/windows64-stable/
> 32-bit: https://toggl.github.io/toggldesktop/download/windows-stable/
> 
> Most of the users can also auto-update from About view or by restarting the app.

Installed 64 Bit version. Works perfect. Thanks a lot !

**Comment by kiwirot** [comment] 2020-06-02 11:20
Thanks for the fix. :)
Does anyone know, how long it usally takes, until the update is available for the Windows Store version?

**Comment by skel35** [comment] 2020-06-02 11:23
@kiwirot it's undergoing the Store review by Microsoft since yesterday. Their review takes "up to three business days".

**Comment by kiwirot** [comment] 2020-06-05 09:11
Now, also the Windows Store has updated my Toggl version, and it works nice and smoothly. Many thanks 😀

**Comment by JiaChen-Zeng** [comment] 2021-01-02 15:24
I couldn't log in on the newest version. It showed the same error. Then I didn't know but somehow it recognized my network properly so I logged in. But it shows "Offline, no network" in the main UI.

I'm using a network proxy. That's unacceptable for me to not able to use a proxy. And even the "Do not use proxy" option has no effect at all.

**Comment by pedy711** [comment] 2022-05-03 07:41
For me, it worked with choosing the third option in the proxy window and entering the proxy's IP address and port.
