### ISSUE TITLE
Linux keyboard shortcuts are inconsistent and partially not documented

### ISSUE THREAD

**Issue by sojusnik** [toggl-open-source/toggldesktop#3601] opened 2019-12-08 11:50 UTC
While keyboard shortcuts are documented for [Windows](https://support.toggl.com/en/articles/2410809-toggl-desktop-for-windows) and [Mac](https://support.toggl.com/en/articles/2410817-toggl-desktop-for-mac) (see bottom of the page), they are missing for [Linux](https://support.toggl.com/en/articles/2410832-toggl-desktop-for-linux).

I'm especially missing a shortcut to focus the time entry field (usually SHIFT+DOWN on win & mac).

Other shortcuts like ESC, ENTER, BACKSPACE don't work at all on Linux.
Ideally, ENTER should open a selected entry, ESC leave it (2nd ESC focus on timer) and CTRL+ENTER should apply changes made (analogous to "Done" in the edit window).
At the moment SPACE (or CTRL+ENTER) opens an entry, but this key should actually continue the selected time entry.
Deleting an entry works only with CTRL+DEL, but BACKSPACE is documented for that on other OS.

Happens with v7.4.528 on Ubuntu 19.04.

Can we have consistent keyboard shortcuts across all OS?

**Comment by thomwiggers** [comment] 2020-09-14 09:38
This is probably a partial duplicate of #2260

**Closed** 2020-10-05 15:44 UTC
Labels: bug, linux
