### ISSUE TITLE
"Signin With Apple" prompt to create a new account instead of logging in

### ISSUE THREAD

**Issue by edtamayo** [toggl-open-source/toggldesktop#4240] opened 2020-07-14 19:56 UTC
### 💻 Environment

Platform: macOS
OS Version: macOS 10.15
Toggl Version: 7.5.192

### 🐞 Actual behavior
clicking "Signin With Apple" prompts them to create a new account, instead of logging in with their Apple login

### 💯 Expected behavior
They user should be prompted to sign in with his apple login

### 🔨 Steps to reproduce

1. Open the desktop app
2. Try to sign in with apple
3. The user is then prompted to create a new account

[Case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481300022022)
The conversation below shares details of unusual behavior on the apple sign in feature:

### 📦 Additional info
Slack conversation: https://toggl.slack.com/archives/C029WCX0T/p1594152126441600

Andri wrote a great breakdown on this conversation in slack:

andrii  5 days ago
Jake, not sure I understand the user request... correct me if I'm wrong.
User has Toggl account calebproland@gmail.com
User has Apple ID calebpaulroland@gmail.com
He wants to login with his Apple ID into his Toggl account

andrii  5 days ago
Tried to reproduce the case above and now I have a strange situation.

Preconditions:
Have two Toggl accounts, let's say one@mail.com and two@mail.com
Have Apple ID, let's say one@mail.com
This Apple ID is connected to Toggl account one@mail.com

Steps:
Went to Web app and logged in with one@mail.com (via email + pass)
Opened Profile settings and disable "Apple sign in" for this account
Logged in on Web app with two@mail.com => Profile settings => enable "Apple sign in" with one@mail.com

Result:
When using "Sign in with Apple" on Web - user is logged in as two@mail.com
When using "Sign in with Apple" on desktop - user is logged in as one@mail.com

**Comment by aspearman** [comment] 2020-11-19 08:52
Same here, macOS 11

**Comment by AndrewVebster** [comment] 2020-12-07 11:13
I cannot reproduce the issue now. It's possible that it was fixed 🤔
@aspearman please tell, if you still have issues with Apple Sign In on desktop.

**Comment by aspearman** [comment] 2020-12-07 21:01
@AndrewVebster I can still reproduce it. I signed out on iOS, logged back in using Sign in with Apple, then tried to log in to the macOS version of Toggl and the native Apple prompt/modal asked me to create an account instead of use the existing account I created on iOS. 

This is on iOS 14.2.1, Toggl 2.21.2 (52210200/1)
and macOS 11.0.1, Toggl 7.5.386

I uninstalled and reinstalled Toggl Desktop and could still reproduce the issue.

**Comment by AndrewVebster** [comment] 2020-12-08 12:41
Thanks @aspearman 
I will look into that issue again

**Comment by AndrewVebster** [comment] 2020-12-09 12:34
hey @aspearman 👋 
I believe the issue is fixed, but also I'm not sure when the settings will become active.
Could you please try to reproduce the issue again later today or tomorrow? If it won't work it'd be nice to try reinstalling the app.
And thanks again for the help

**Comment by AndrewVebster** [comment] 2020-12-11 08:45
Closing it as fixed

**Closed by AndrewVebster** 2020-12-11 08:45 UTC
Labels: bug, macOS

**Comment by aspearman** [comment] 2020-12-11 23:09
Sorry, just got around to testing it. I can confirm it now asks to sign in rather than sign up, so it's fixed. 👍🏻

**Comment by AndrewVebster** [comment] 2020-12-12 08:10
@aspearman thank you 👍
