### ISSUE TITLE
Desktop App not switching colors completely when MacOS appearance settings are changed

### ISSUE THREAD

**Issue by edtamayo** [toggl-open-source/toggldesktop#4193] opened 2020-06-18 17:45 UTC
### 💻 Environment

Platform: macOS
OS Version: macOS Catalina version 10.15.5.
Toggl Version: 7.5.172 Stable

### 🐞 Actual behavior

When changing the display setting from Dark to light and vice-versa on Mac's System Preferences > General > Appearance while the Desktop app has an Edit time entry pop up, the main Desktop App window color changes but the Edit Time entry pop up does not change color, restarting the app is necessary to apply color changes.

### 💯 Expected behavior

All windows from the Desktop app should change colors with no issues after changing the MacOS display setting preferences

### 🔨 Steps to reproduce

1. Open the Toggl Desktop App
2. Start a running entry and leave the Edit Entry pop up showing
3. On Mac, go to System Preferences > General > Appearance > And change from light to dark or vice versa

### 📦 Additional info

![image](https://user-images.githubusercontent.com/61245582/85054156-7c5a1580-b150-11ea-89d4-ee2848474128.png)

**Comment by edtamayo** [comment] 2020-06-18 17:46
[Case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/27525024948)

**Comment by skel35** [comment] 2020-06-19 07:04
duplicate of #3160

**Closed by skel35** 2020-06-19 07:04 UTC
