### ISSUE TITLE
Changing timezone on windows causes app to crash.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl-open-source/toggldesktop#3358] opened 2019-09-24 21:39 UTC
### 💻 Environment
Platform:Windows 10 Home
OS Version: Version 10.0.18362 Build 18362
Toggl Version: 7.4.529

### 🐞 Actual behavior
The app crashes when attempting to stop the timer

### 💯 Expected behavior
The timer to stop

### 🔨 Steps to reproduce

1. Have a timer running
2. Change the time zone in the windows clock from UTC -8 to UTC -5
3. Try to stop the timer
4. The app crashes continually

### 📦 Additional info
[case] (https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/23755917846)

**Comment by nidarasheed** [comment] 2020-01-29 07:33
Any update on this?

**Comment by skel35** [comment] 2020-02-04 10:46
I was not able to reproduce this issue anymore, although I remember I reproduced it in September.
Either it was a backend bug that is already fixed, or it only occurs during the daylight saving time.
I suggest trying it again in March when the daylight savings is on and close the issue if we cannot reproduce it then.

**Comment by skel35** [comment] 2020-05-26 16:03
Wasn't able to reproduce the issue.
Probably a backend bug that has been fixed by now.
If you can still reproduce, please reopen (mentioning both Windows timezones and profile timezone, and whether "Set time automatically" and "Set time zone automatically" are on in Windows settings.

**Closed by skel35** 2020-05-26 16:03 UTC
Labels: windows
