### ISSUE TITLE
Description field gets overwritten sometimes

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#4549] opened 2020-10-16 09:03 UTC
### 💻 Environment

Platform:  macOS
OS Version:  macOS 10.15.6
Toggl Version:  7.5.298

### 🐞 Actual behavior
When starting a new TE from existing one, if after it starts, you try to edit the description, it sometimes gets overwritten. 

### 💯 Expected behavior
Description box should not overwrite 

### 🔨 Steps to reproduce
[Video here. 
](https://toggl.slack.com/archives/C029WCX0T/p1602838975147500)
### 📦 Additional info
[User Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481304714340)

**Comment by AndrewVebster** [comment] 2020-10-16 09:21
Closing as a duplicate of #4476

**Closed by AndrewVebster** 2020-10-16 09:21 UTC
