### ISSUE TITLE
Pomodoro changes manually entered duration in running timer

### ISSUE THREAD

**Issue by lise-toggl** [toggl-open-source/toggldesktop#3007] opened 2019-06-07 04:07 UTC
### 💻 Environment

Platform: Windows
OS Version: 10
Toggl Version: 7.4.422

### 🐞 Actual behavior
When entering a duration in the live timer, longer than the Pomodoro duration, the timer will stop and the new entry's duration will change to the Pomodoro duration.

### 💯 Expected behavior
The new entry should have the duration you specified.

### 🔨 Steps to reproduce

1. Turn on Pomodoro
2. Start a timer
3. Change the duration to something large, e.g. 50m
4. The new entry's duration will be what you entered
5. After a second, the duration will change to 25m (or whatever your Pomo block is set to)

**Comment by lise-toggl** [comment] 2019-06-07 04:08
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/22348705903)

**Comment by IndrekV** [comment] 2019-06-07 07:47
This is currently so by design. It mostly accounts the situation when the user is actively tracking and then users want the Pomodoro notification to trigger at the correct moment and the time to be stopped with exactly the correct duration.

I understand that manually editing running timer would need to be an exception because it's not intuitive that when you edit the duration it is overwritten a second later.

**Comment by IndrekV** [comment] 2019-06-07 07:48
This is a library issue and not specifically tied to a platform.

**Comment by nidarasheed** [comment] 2019-08-08 07:35
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23168033664)

**Comment by skel35** [comment] 2020-05-26 15:44
Fixed by #3659

**Closed by skel35** 2020-05-26 15:44 UTC
Labels: lib
