### ISSUE TITLE
Investigate memory leak on windows

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1720] opened 2015-12-07 07:45 UTC
> Memory leak on Windows 7 after prolonged usage. Toggl is currently up to 120MB of memory usage (before closing) after starting at 65MB. Includes a couple days of uptime.

**Comment by kadrihvl** [comment] 2015-12-07 07:59
Reported with desk case #225662

**Comment by byronwall** [comment] 2015-12-07 15:16
I reported this via the feedback mechanism in the program.  If there's more info you need/want me to report, let me know.  I have not been watching for specific actions that increase memory usage but have noticed the general trend of increasing usage over time.

**Comment by amulware** [comment] 2015-12-07 15:45
It could be that the 120MB observed is just .NET reserving space and being lazy with its garbage collection (in which case this should not increase much higher than this). However, it does sound like a lot, given that the app uses only around 30MB for me (though this is a test account with hardly any data).

@byronwall:
Can you confirm whether the memory usage increases slowly over time, or in large steps?
Also, if you happen to get into the situation where it uses >100Mb again, could you try logging out and back in (without closing the app), and then clearing cache and logging back in (again without closing the app), and see how this affects memory usage?

I'll also start a long term test and see if I can reproduce the issue.

**Comment by byronwall** [comment] 2015-12-07 16:36
I'll get a log together of the memory usage over time.  I set up a data collector on TogglDesktop inside perfmon.  We'll see what the memory usage looks like over time.

Once it gathers data for a day or so, I will do the steps you mention to log out/clear cache/etc.

**Comment by byronwall** [comment] 2015-12-10 17:32
@amulware 
I have been collecting data for the last several days.  Included is a CSV file with the output from perfmon.  It includes all the available counters for Toggl.  I suspect the amount of data is overkill, but it's easier to include them all rather than filter.

To answer the question about how the memory is being consumed, there appears to be a slow increase over time with periods of increase and decrease superimposed.  The slow increases at night are most telling since the program is sitting there on its own.  I think the spikes during the day are associated with me using the program.

I did the steps related to clearing the cache and logging in/out several times.  I see no significant drop in memory usage after doing those steps.

This is the increase in memory usage over the last several days:
![image](https://cloud.githubusercontent.com/assets/495404/11722856/84f6d3e8-9f28-11e5-8192-cc90e6b8698d.png)

Here is same data point (Working Set [MB]) with 1 second resolution while doing the cache clearing and logging out.  There was no impact on memory.  Closing the program and restarting leads to the major drop.
![image](https://cloud.githubusercontent.com/assets/495404/11722947/0e1d2654-9f29-11e5-96d2-be60bc9e2140.png)

**Comment by byronwall** [comment] 2015-12-10 17:36
Here is the data.  I guess you can't attach files here...

https://gist.github.com/byronwall/63a63af88053445a84a0

**Comment by amulware** [comment] 2015-12-11 09:23
Thanks for the detailed information!

This indeed looks very much like a memory leak.

We will definitely look into this further.

**Comment by amulware** [comment] 2015-12-17 08:02
@tanel:

Could you take a look at the log file (see the case id above)?
The (vast) beginning of it looks like idle time by the user. There are no updates of the UI, but a large number of what seem to be identical /me requests (All returning with Content-Length: 994, so most likely the same responses), every 30 minutes or so.

It also shows several idle reminders between each request.

Something within this idle behaviour seems to leak.
Can you take a look if there is anything in the library that could be the problem?
(Could it be something silly like keeping the entire log in memory, or something?)
I will also see if I can find anything about the idle reminders that looks fishy.

**Comment by amulware** [comment] 2016-02-01 08:13
While it is still not clear what causes the leak, we got a report from a linux user for whom Toggl Desktop used **more than 4GB** of memory after leaving it running idle for a weekend (see case 245807)

This makes me suspect even more that the leak is probably in some library system that is active even when idle.

**Comment by tr00st** [comment] 2019-02-12 09:20
Issue still occurs as of 7.4.252 (seeing RAM usage upwards of 500MB on Win10 after long running sessions)

**Comment by skel35** [comment] 2020-05-13 12:50
Closing this issue as several memory leak problems were fixed since.

**Closed by skel35** 2020-05-13 12:50 UTC
Labels: bug, lib
