### ISSUE TITLE
Toggl icon still appears in the Dock even when the setting is turned off

### ISSUE THREAD

**Issue by zdericnina** [toggl-open-source/toggldesktop#4117] opened 2020-05-29 12:41 UTC
### 💻 Environment

Platform:  macOS
OS Version:  macOS 10.15.4
Toggl Version:  7.5.146

### 🐞 Actual behavior

In TogglDesktop preferences, the Show dock option is turned off but the Toggl still appears in the Dock.

### 💯 Expected behavior

If the setting for Show dock icon is turned off, Toggl shouldn't appear in the dock

### 🔨 Steps to reproduce

I was able to replicate it using these steps:

1. Make sure that `Show recent applications in Dock` is checked in Dock preferences
2. Go to TogglDesktop - Preferences - uncheck the option for `Show dock icon`
3. Toggl icon will still remain in the Dock

### 📦 Additional info

If `Show recent applications in Dock` isn't checked in Dock preferences, Toggl icon will disappear as it should.

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/2759100/conversations/27282211045) it includes the video of user replicating the issue

**Comment by urbantrout** [comment] 2020-05-30 18:39
I'm having the exact same issues since the 7.5.146 release although. In my case it doesn't matter whether I have **Show recent applications in Dock** enabled or not.

**Comment by NghiaTranUIT** [comment] 2020-06-05 07:06
I just double-check and it's correct behavior on macOS.

### If "Show recent applications in Dock" is enabled
- All apps will keep present on the dock (In the Recent Area) regardless of the "Show dock icon" setting because it's how it works. 

### If "Show recent applications in Dock" is disabled
- The app icon will respect show/dismiss depend on the setting "Show dock icon", except if the app is persisted in the lock area (By dragging the app to the dock, and the icon will appear even though the app is quitted). 

I suppose that it's what @urbantrout encountered. Please drag it out the dock to remove it, then it will work

**Comment by urbantrout** [comment] 2020-06-05 08:35
Here's a screencast

![out](https://user-images.githubusercontent.com/10465787/83855220-0d27fe80-a718-11ea-91a3-d187c889fccc.gif)

I'm using the global keyboard shortcuts to show and hide toggl (see keyboard input in the left bottom corner)
As soon as I open the toggl preferences the dock icon disappears again.

**Comment by NghiaTranUIT** [comment] 2020-06-05 08:48
I see, thanks for the screencast. We will investigate and fix it 👍

**Comment by Leksat** [comment] 2020-06-15 15:21
Same here. I noticed that if I close the Toggle window with the `x` icon in the app header, it works just fine. But if I close it with the global shortcut, the app icon appears in the dock.

**Comment by VeljkoTN** [comment] 2020-06-18 11:00
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300000647)

**Comment by rishifter** [comment] 2020-06-21 11:34
Same issue here. I've always had the recent apps on dock enabled and Toggl didn't show up in Dock before. The reason it's an issue is when using full screen apps on the Mac and triggering Toggl with the global shortcut, it always worked as a popup but now it switches the Desktop/space away from the full screen app because of the icon in the Dock.

**Comment by dianetoggl** [comment] 2020-07-21 21:57
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481300033679) This user is also experiencing duplicating dock icons when they hide/show the Toggl application. Video in Intercom 😊

**Comment by freinbichler** [comment] 2020-07-22 07:42
I am also eagerly awaiting a fix for this issue. My issue is exactly the same as seen in the screencast shown in https://github.com/toggl-open-source/toggldesktop/issues/4117#issuecomment-639340557 above.

**Comment by edtamayo** [comment] 2020-07-22 18:09
[Case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481300016401)
Referencing @dianetoggl  comment, I was able to reproduce the multiple dock icons when testing this as well

**Comment by AndrewVebster** [comment] 2020-07-24 14:20
Did a quick fix. It's in the review but you can try it now by downloading it from https://github.com/toggl-open-source/toggldesktop/actions/runs/181238547

It works on my machine, but I'm also interested in testing it on older macOS versions. So if you have one, would be thankful for the testing 🙂

**Comment by rishifter** [comment] 2020-07-24 15:19
@AndrewVebster It works fine here on Catalina. It shows version 7.0.0 though.

**Comment by AndrewVebster** [comment] 2020-07-24 15:36
it's okay that it shows v7.0.0, it's just a test build

**Closed** 2020-07-24 15:47 UTC
Labels: bug, macOS
