### ISSUE TITLE
"Stop time year must be between 2006 and 2030" Error

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#3193] opened 2019-08-08 17:21 UTC
### 💻 Environment

Platform: macOS
OS Version: Current
Toggl Version: 7.4.484 

### 🐞 Actual behavior
When starting an entry by clicking on an older entry's play button, an error message appears at the bottom of the app screen stating "Stop time year must be between 2006 and 2030" 

User experiencing this; I cannot replicate

### 📦 Additional info
[Link](https://toggl.slack.com/archives/C029WCX0T/p1565194235087500) of Slack convo
[Link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/23148809600) of Intercom convo

**Comment by lise-toggl** [comment] 2019-08-21 02:13
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23330344442)

**Comment by nidarasheed** [comment] 2019-08-22 08:54
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23354872095)

**Comment by lise-toggl** [comment] 2019-08-28 00:54
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23425505887) - happens when they edit the start time of a currently running time entry

**Comment by skel35** [comment] 2020-07-01 08:29
just reproduced it. my steps
- Start a time entry (at around 11:20 am)
- Change the start time to 10:00 am
- Stop a time entry and start a new one
- Edit stop time of a stopped entry to 10:05 am
- Edit start time of a running entry (type "1005" into the start time field)

**Comment by TheSoloJake** [comment] 2020-07-01 14:10
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300018973)

**Comment by nicktoggl** [comment] 2020-08-20 00:32
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481300008313)

**Comment by nicktoggl** [comment] 2020-11-06 01:21
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481305545779)

**Comment by skel35** [comment] 2020-11-24 15:22
[Internal report](https://toggl.slack.com/archives/C029WCX0T/p1606230809360400)

**Comment by AndrewVebster** [comment] 2020-12-07 10:24
Hey 👋 I need help reproducing this issue. I've spent a lot of time on this without any luck.
@skel35 can you still reproduce the bug with your steps above?

**Comment by skel35** [comment] 2020-12-07 11:16
sure, will try this out in a few mins

**Comment by skel35** [comment] 2020-12-07 12:07
I can't reproduce it with the steps above anymore.
Looking at Bugsnag, the issue has occurred to at least 298 users, all on macOS, and keeps happening until now, so we should keep investigating and find the appropriate steps.

In [the case above](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481305545779) I've noticed the following line:
>database:D:Updating time entry TimeEntry ID=1759145974 local_id=320 description=X1-159 uid=5237793 wid=3804800 guid=d4b5141f-bb75-407e-9d82-cb7150262526 pid=155779897 tid=0 start=1604595752 stop=86400 duration=-1604595752 billable=0 unsynced=0 duronly=0 tags= created_with=osx_native_app/7.5.286 ui_modified_at=1604599372 deleted_at=0 updated_at=1604599353 in thread 0x10fdc7dc0

The curious part is `stop=86400` - meaning Stop time is assigned to 24h after the beginning of unix time. That at least gives the clue on how this can be fixed.

**Comment by AndrewVebster** [comment] 2020-12-07 12:12
Thanks @skel35 
Just one more question. Are you sure that you log this event on Windows? Want to know if this is a platform issue.
BTW after v7.5.363 this specific error is not logged to Bugsnag anymore.

**Comment by skel35** [comment] 2020-12-07 12:19
It's not logged anymore because we stopped logging it after this: https://github.com/toggl-open-source/toggldesktop/pull/4640.

I've found that it has happened on Windows too, but it's 2 users on Windows vs 445 users on macOS:
https://app.bugsnag.com/toggldesktop/toggldesktop/errors/5ced0ede39a4680019589d0d?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=Stop&filters[search][1][type]=eq&filters[search][1][value]=time&filters[search][2][type]=eq&filters[search][2][value]=year&filters[search][3][type]=eq&filters[search][3][value]=must&filters[search][4][type]=eq&filters[search][4][value]=be&filters[search][5][type]=eq&filters[search][5][value]=between&filters[search][6][type]=eq&filters[search][6][value]=2006&filters[search][7][type]=eq&filters[search][7][value]=and&filters[search][8][type]=eq&filters[search][8][value]=2030

**Comment by skel35** [comment] 2020-12-07 13:21
In all of the cases there is another error in the logs happening right before the time entry has `stop=86400`:
>2019-08-22 08:36:21.343 [2573 0]:Formatter:W:Parsed timestamp is too small, will interpret as 0: 31800
2019-08-22 08:36:21.343 [2573 0]:time_entry:E:Stop time must be after start time!

or
>2020-11-05 18:02:46.836 [15608 0]:Formatter:W:Parsed timestamp is too small, will interpret as 0: -25080
2020-11-05 18:02:46.836 [15608 0]:time_entry:E:Stop time must be after start time!

**Closed** 2020-12-08 11:19 UTC
Labels: bug, lib, macOS
