### ISSUE TITLE
Toggl Desktop Windows 7.4.252 - Pomodoro/Manual mode issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#2773] opened 2019-01-25 10:33 UTC
### 💻 Environment

Platform: windows_native_app/7.4.252-obm-87-obm-98-obm-99-obm-101
OS Version: Windows 10
Toggl Version: 7.4.252 (stable)

### 🐞 Actual behavior

If you enable Pomodoro and try to create a TE in manual mode setting its duration longer than the duration set for triggering the Pomodoro notification the app will not let you save the TE and it will trigger the Pomodoro notification right away. 

### 💯 Expected behavior
You should be able to create a time entry in manual mode of any duration you wish, no matter what your settings are for Pomodoro. 

### 🔨 Steps to reproduce

1. Enable Pomodoro (leave at 25 minutes or set a custom value)
2. Go into manual mode
3. Create a TE that's longer that the Pomodoro setting (in this case longer than 25 minutes or your custom value)

The app will trigger a Pomodoro notification immediately asking you if you wish to stop or continue tracking. If you click continue it will just reopen the side-window for entering details of a new TE.

**Comment by zdericnina** [comment] 2019-03-15 15:15
case reporting this(https://app.intercom.io/a/apps/ayixs927/inbox/conversation/21199129935)

**Comment by TheSoloJake** [comment] 2019-03-15 15:18
[Case link](https://app.intercom.io/a/apps/ayixs927/inbox/conversation/21199129935)

**Comment by NghiaTranUIT** [comment] 2019-12-27 10:00
Even thought this issue is causes from the Library's logic, but I couldn't reproduce it in macOS build (Beta 7.4.1106).
- Able to Create a TE that's longer that the Pomodoro setting (in this case longer than 25 minutes or your custom value) in Manual mode

**Comment by skel35** [comment] 2020-05-26 15:35
Fixed by #3659

**Closed by skel35** 2020-05-26 15:35 UTC
Labels: bug, windows
